# Generated by Django 4.1.7 on 2023-03-20 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('site', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Artistas',
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VideoAulas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('site', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('tom', models.CharField(max_length=10)),
                ('videoaula', models.URLField(blank=True, null=True)),
                ('artistas', models.ManyToManyField(related_name='musicas', to='socifras.artista')),
                ('generos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='musicas', to='socifras.genero')),
                ('videoaulas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='musicas', to='socifras.videoaulas')),
            ],
        ),
    ]
