# Generated by Django 4.1.7 on 2023-03-30 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socifras', '0002_musica_capa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musica',
            old_name='titulo',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='videoaulas',
            old_name='descricao',
            new_name='nome',
        ),
        migrations.RemoveField(
            model_name='artista',
            name='site',
        ),
        migrations.RemoveField(
            model_name='musica',
            name='capa',
        ),
        migrations.RemoveField(
            model_name='musica',
            name='tom',
        ),
    ]
