# Generated by Django 4.2 on 2023-04-03 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socifras', '0003_rename_titulo_musica_nome_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musica',
            old_name='artistas',
            new_name='artista',
        ),
        migrations.RenameField(
            model_name='musica',
            old_name='generos',
            new_name='genero',
        ),
        migrations.RemoveField(
            model_name='musica',
            name='videoaula',
        ),
    ]
